version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: wifi-backend
    ports:
      - "8088:8088"
    volumes:
      - /var/log/wifi-metrics.csv:/var/log/wifi-metrics.csv:ro
      - ./dashboard/main.py:/app/main.py
    env_file:
      - .env
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: docker/dashboard/Dockerfile
    container_name: wifi-dashboard
    ports:
      - "8090:80"
    depends_on:
      - backend
    restart: unless-stopped

  metrics:
    build:
      context: .
      dockerfile: docker/metrics/Dockerfile
    container_name: wifi-metrics
    network_mode: host
    volumes:
      - /var/log/wifi-metrics.csv:/var/log/wifi-metrics.csv
    restart: unless-stopped

